//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KungFuPanda
{
    using System;
    using System.Collections.Generic;
    
    public partial class sni
    {
        public int INSTRUCTOR_ID { get; set; }
        public string INSTRUCTOR_NAME { get; set; }
        public string INSTRUCTOR_PASSWORD { get; set; }
        public Nullable<bool> INSTRUCTOR_STATUS { get; set; }
        public string INSTRUCTOR_EMAIL { get; set; }
        public string INSTRICTOR_MNUM { get; set; }
    }
}
