//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KungFuPanda
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAttendence
    {
        public int ATT_ID { get; set; }
        public Nullable<int> CLASS_ID { get; set; }
        public Nullable<int> STU_ID { get; set; }
        public Nullable<System.DateTime> ATT_DATE { get; set; }
        public Nullable<bool> ATT_STATUS { get; set; }
        public Nullable<int> ATT_CREATED_BY { get; set; }
        public Nullable<System.DateTime> ATT_CREATED_DATE { get; set; }
        public Nullable<int> ATT_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> ATT_MODIFIED_DATE { get; set; }
    
        public virtual tblClass tblClass { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
