//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KungFuPanda
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClassLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClassLevel()
        {
            this.tblClasses = new HashSet<tblClass>();
        }
    
        public int CLASS_LEVEL_ID { get; set; }
        public string CLASS_LEVEL_NAME { get; set; }
        public Nullable<int> CLASS_LEVEL_CREATED_BY { get; set; }
        public Nullable<System.DateTime> CLASS_LEVEL_CREATED_DATE { get; set; }
        public Nullable<int> CLASS_LEVEL_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> CLASS_LEVEL_MODIFIED_DATE { get; set; }
        public Nullable<bool> CLASS_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblClass> tblClasses { get; set; }
    }
}
