//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KungFuPanda
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblClass()
        {
            this.tblAttendences = new HashSet<tblAttendence>();
        }
    
        public int CLASS_ID { get; set; }
        public Nullable<int> CLASS_LEVEL_ID { get; set; }
        public string CLASS_DAY { get; set; }
        public string CLASS_TIME { get; set; }
        public Nullable<bool> CLASS_STATUS { get; set; }
        public Nullable<int> CLASS_CREATED_BY { get; set; }
        public Nullable<System.DateTime> CLASS_CREATED_DATE { get; set; }
        public Nullable<int> CLASS_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> CLASS_MODIFIED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendence> tblAttendences { get; set; }
        public virtual tblClassLevel tblClassLevel { get; set; }
    }
}
