//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KungFuPanda
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayment
    {
        public int PAYMENT_ID { get; set; }
        public Nullable<int> PAYMENT_TYPE_ID { get; set; }
        public Nullable<decimal> PAYMENT_AMOUNT { get; set; }
        public Nullable<int> STU_ID { get; set; }
        public Nullable<bool> PAYMENT_STATUS { get; set; }
        public Nullable<System.DateTime> PAYMENT_DATE { get; set; }
        public Nullable<int> PAYMENT_CREATED_BY { get; set; }
        public Nullable<System.DateTime> PAYMENT_CREATED_DATE { get; set; }
        public Nullable<int> PAYMENT_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> PAYMENT_MODIFIED_DATE { get; set; }
    
        public virtual tblPaymentType tblPaymentType { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
