//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KungFuPanda
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblRank()
        {
            this.tblStudentProgresses = new HashSet<tblStudentProgress>();
        }
    
        public int RANK_ID { get; set; }
        public string RANK_BELT_COLOR { get; set; }
        public string RANK_REQUIREMENTS { get; set; }
        public Nullable<bool> RANK_STATUS { get; set; }
        public Nullable<bool> RANK_IS_DEFAULT { get; set; }
        public Nullable<int> RANK_CREATED_BY { get; set; }
        public Nullable<System.DateTime> RANK_CREATED_DATE { get; set; }
        public Nullable<int> RANK_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> RANK_MODIFIED_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentProgress> tblStudentProgresses { get; set; }
    }
}
