//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KungFuPanda
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentProgress
    {
        public int STU_PROG_ID { get; set; }
        public Nullable<int> STU_ID { get; set; }
        public Nullable<int> RANK_ID { get; set; }
        public Nullable<System.DateTime> STU_PROG_RANK_DATE { get; set; }
        public Nullable<bool> STU_PROG_STATUS { get; set; }
        public Nullable<int> STU_PROG_CREATED_BY { get; set; }
        public Nullable<System.DateTime> STU_PROG_CREATED_DATE { get; set; }
        public Nullable<int> STU_PROG_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> STU_PROG_MODIFIED_DATE { get; set; }
    
        public virtual tblRank tblRank { get; set; }
        public virtual tblStudent tblStudent { get; set; }
    }
}
