//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KungFuPanda
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblStudent()
        {
            this.tblAttendences = new HashSet<tblAttendence>();
            this.tblParents = new HashSet<tblParent>();
            this.tblPayments = new HashSet<tblPayment>();
            this.tblStudentProgresses = new HashSet<tblStudentProgress>();
        }
    
        public int STU_ID { get; set; }
        public string STU_NUM { get; set; }
        public string STU_FNAME { get; set; }
        public string STU_MNAME { get; set; }
        public string STU_LNAME { get; set; }
        public Nullable<System.DateTime> STU_DOB { get; set; }
        public Nullable<System.DateTime> STU_DOJ { get; set; }
        public string STU_MNUM { get; set; }
        public string STU_EMAIL { get; set; }
        public string STU_STREET { get; set; }
        public string STU_CITY { get; set; }
        public string STU_STATE { get; set; }
        public string STU_ZIP { get; set; }
        public Nullable<bool> STU_STATUS { get; set; }
        public Nullable<int> STU_CREATED_BY { get; set; }
        public Nullable<System.DateTime> STU_CREATED_DATE { get; set; }
        public Nullable<int> STU_MODIFY_BY { get; set; }
        public Nullable<System.DateTime> STU_MODIFIED_DATE { get; set; }
        public Nullable<bool> STU_GENDER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAttendence> tblAttendences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblParent> tblParents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPayment> tblPayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblStudentProgress> tblStudentProgresses { get; set; }
    }
}
